---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: backend
spec:
  encryptedData:
    REDIS_PASSWORD: AgAsIPVkRxCpxjYvfw8bQ3yR0sd7PqrY667IkjcHUcgswM7uRRnRdtnv3ZNiIkvcieBfIrY8YHCEUAPxS8eXANHC/341xral9LErvZxxuIHLPwaxAH67glvyQbdLtC6mO/KkQYTXc8xQYyao/tSRiCaDnqedswwdfQLNge419ivx30Q1RQBrd+3+dQ972gDCYC8e1T96i642PeG69g1IQjcal5tv+7yb4SZAfXNImsuCjh5acD7dPfI5yTWEbnNU9zqKa21LhnWyuuhqeeHVgxKer5qohOvOybqCSJrSGb0Q5xMv8l6y7/xqPVN0oGrYFIVC4TimFMLaustfd3FEJio98OcyNBZT6aVS3GnAsY68eHgKcWQ96vnvDaTzC3NWuH5CRNaMXOgxDnRNoKJe30RWCiLfskhrgFAGVumDJO2yvLPaCGDoQSopL1YCxE/yscO3xPCPD7fnDKyKxqcD3iUSl6t21PGNXMaCI4jQoD1saHwfWiwzM61wlK4nECFSBn1nqFBYKuisqnzG7U89v8TYkMCxwJL0e4ekBTZMTEfnF5W6UFOJuFWRQPk/g+/mYyOWTeK9hsSOw3/RF9BdF1KViZGVjBaWJYxn2eRdja07E3YDwOP8mtt4oYh1hM0GP8zbqCwOKVa3cUMKO4bZrFmRPr8dRllLfAS5Vkf+dIwRuWitSNYpx+tK2h7RyeJ1/p0SJjb6Q5AL44bCc5KL
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: backend
    type: Opaque
