---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: backend
spec:
  encryptedData:
    REDIS_PASSWORD: AgAO/VUwutu4atThMxzpUF9rrMeUAuvWYL5XpJOqxeSMnko5uptGjcvjjaR4HoMOl1nOcCfZGsO+KoJQ/z1FxcTcBEIvEUkN1zxtJ1e+jhcT8yPNjuev0/Y431o2abiER+M3r3eI/kdsHe+zNRpVHmNhcEXh6MxEk64U7np8/Dbxq+YoWbsbBlb3IugLu8cNXxyPOlpEkwD/6nS8Vtas0fNVB0kf6LBkksWubiZF1b5XXcwASkLGPZez/ZvmV7HBW0MoBFXJL04cR+EbnJ/t3WFkhos8xbVSZcqR3/UZNfk7bjG1o//QCSgzrTbZ09MmbxXDR5zl6liKxv61FHQpHMIAtEM5L6ferOTBX+8bghEyCTazWaDDnfKzpyZALdIEn4S+BK8zwqV2/IYwBkEmvPtgXmRuSQwSY/GQTCpYz5k6vw0Eqv2XYdQuzuDmAvzA3FP0o2JemnxvZoL42qEXRpXAxIzeqFc+ZkT3A4GnYbXLv2kE6oYlvWSvYFY9irXdOi+ArGoXvsWU5NFA2hEdHdr/5mRjrLKCuv6JF60GQ9C73J9OoERFIjKa4F7H7CVGojNiULhZORBKM7+cnYv0tCIP+Gj86Kqw9+g/pyn62OQMQBM+hxMgLStpfN+0aXtYT2db1J0HBVD5VrB8BdE/phR4gQeCqkGlsQKRqCdNIzIqekaqbaKVFER9XOlCOwjk5ZJD+3HqHgFggtm9lw+1
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: backend
    type: Opaque
