apiVersion: batch/v1
kind: Job
metadata:
  name: habit-db-init
  namespace: {{ .Values.db.namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: habit-db-init
          image: {{ .Values.db.image }}
          command:
            - /bin/sh
            - -c
            - |
              until pg_isready -h habit-db.{{ .Values.db.namespace }}.svc.cluster.local -p {{ .Values.db.port }} -U postgres; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
              PGPASSWORD={{ .Values.db.password }} psql -h habit-db.{{ .Values.db.namespace }}.svc.cluster.local -p {{ .Values.db.port }} -U postgres -c "CREATE DATABASE {{ .Values.db.name }};" || true
              PGPASSWORD={{ .Values.db.password }} psql -h habit-db.{{ .Values.db.namespace }}.svc.cluster.local -p {{ .Values.db.port }} -U postgres -c "CREATE USER {{ .Values.db.user }} WITH PASSWORD '{{ .Values.db.password }}';" || true
              PGPASSWORD={{ .Values.db.password }} psql -h habit-db.{{ .Values.db.namespace }}.svc.cluster.local -p {{ .Values.db.port }} -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE {{ .Values.db.name }} TO {{ .Values.db.user }};" || true
  backoffLimit: 3
