apiVersion: v1
kind: Secret
metadata:
  name: habit-db-secret
  namespace: db
type: Opaque
data:
  POSTGRES_PASSWORD: "aGFiaXRwYXNzd29yZA=="
  POSTGRES_USER: "aGFiaXR1c2Vy"
  POSTGRES_DB: "aGFiaXRkYg=="
