habitService:
  image:
    repository: rnld101/lavenbloom-habit-service
    tag: dev-1e633492c8774fe561b1f66f1ae1ce0ab80bf9f3
  replicas: 1
  port: 8000
  namespace: backend
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
db:
  namespace: db
  image: postgres:16-alpine
  replicas: 1
  port: 5432
  storage:
    size: 5Gi
global:
  storageClass: nfs
