apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  {{- if .Values.gateway.parametersRef }}
  infrastructure:
    parametersRef:
      group: {{ .Values.gateway.parametersRef.group }}
      kind: {{ .Values.gateway.parametersRef.kind }}
      name: {{ .Values.gateway.parametersRef.name }}
  {{- end }}
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      allowedRoutes:
        namespaces:
          from: All
    {{- end }}
