apiVersion: v1
kind: Secret
metadata:
  name: notification-db-secret
  namespace: db
type: Opaque
data:
  POSTGRES_PASSWORD: "bm90aWZpY2F0aW9ucGFzc3dvcmQ="
  POSTGRES_USER: "bm90aWZpY2F0aW9udXNlcg=="
  POSTGRES_DB: "bm90aWZpY2F0aW9uZGI="
