apiVersion: v1
kind: Service
metadata:
  name: notification-db
  namespace: {{ .Values.db.namespace }}
  labels:
    app: notification-db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    app: notification-db
---
apiVersion: v1
kind: Service
metadata:
  name: notification-db-headless
  namespace: {{ .Values.db.namespace }}
  labels:
    app: notification-db
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    app: notification-db
