apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notification-db
  namespace: {{ .Values.db.namespace }}
  labels:
    app: notification-db
spec:
  serviceName: notification-db-headless
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: notification-db
  template:
    metadata:
      labels:
        app: notification-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.db.port }}
          envFrom:
            - secretRef:
                name: notification-db-secret
          volumeMounts:
            - name: notification-db-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
  volumeClaimTemplates:
    - metadata:
        name: notification-db-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.global.storageClass }}
        resources:
          requests:
            storage: {{ .Values.db.storage.size }}
