apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-microservices
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/lavenbloom/lavenbloom-charts
        revision: main
        directories:
          - path: ./microservices/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: lavenbloom
      source:
        repoURL: https://github.com/lavenbloom/lavenbloom-charts
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - values-prod.yaml
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
