apiVersion: apps/v1
kind: Deployment
metadata:
  name: habit-service
  namespace: {{ .Values.habitService.namespace }}
  labels:
    app: habit-service
    tier: backend
spec:
  replicas: {{ .Values.habitService.replicas }}
  selector:
    matchLabels:
      app: habit-service
  template:
    metadata:
      labels:
        app: habit-service
        tier: backend
    spec:
      containers:
        - name: habit-service
          image: "{{ .Values.habitService.image.repository }}:{{ .Values.habitService.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.habitService.port }}
          envFrom:
            - secretRef:
                name: habit-service-secret
          resources:
            requests:
              cpu: {{ .Values.habitService.resources.requests.cpu }}
              memory: {{ .Values.habitService.resources.requests.memory }}
            limits:
              cpu: {{ .Values.habitService.resources.limits.cpu }}
              memory: {{ .Values.habitService.resources.limits.memory }}
