apiVersion: v1
kind: Secret
metadata:
  name: habit-service-secret
  namespace: backend
type: Opaque
data:
  POSTGRES_URI: "cG9zdGdyZXNxbDovL2hhYml0dXNlcjpoYWJpdHBhc3N3b3JkQGhhYml0LWRiLmRiLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvaGFiaXRkYg=="
  JWT_SECRET: "c3VwZXJzZWNyZXRqd3RrZXk="
  REDIS_URI: "cmVkaXM6Ly86cmVkaXNwYXNzd29yZEByZWRpcy5iYWNrZW5kLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzkvMA=="
