apiVersion: v1
kind: Secret
metadata:
  name: habit-service-secret
  namespace: {{ .Values.habitService.namespace }}
type: Opaque
data:
  POSTGRES_URI: {{ .Values.secrets.postgresUri | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  REDIS_URI: {{ .Values.secrets.redisUri | b64enc | quote }}
