apiVersion: v1
kind: Service
metadata:
  name: habit-service
  namespace: {{ .Values.habit-service.namespace }}
  labels:
    app: habit-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.habit-service.port }}
      targetPort: {{ .Values.habit-service.port }}
  selector:
    app: habit-service
