apiVersion: v1
kind: Secret
metadata:
  name: journal-db-secret
  namespace: db
type: Opaque
data:
  POSTGRES_PASSWORD: "am91cm5hbHBhc3N3b3Jk"
  POSTGRES_USER: "am91cm5hbHVzZXI="
  POSTGRES_DB: "am91cm5hbGRi"
