frontend:
  image:
    repository: rnld101/lavenbloom-frontend
    tag: dev-6f9492343f1b20c7eade9b9bfa8b93c08b6064a0
  replicas: 1
  port: 80
  namespace: frontend
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi
