frontend:
  image:
    repository: rnld101/lavenbloom-frontend
    tag: dev-a54ab138dde9c5f0ab866e4599eecfbec3173a88
  replicas: 1
  port: 80
  namespace: frontend
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi
