frontend:
  image:
    repository: rnld101/lavenbloom-frontend
    tag: dev-ec08c17a049e63c770e8bf2646ffac91bc764bdc
  replicas: 1
  port: 80
  namespace: frontend
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi
