frontend:
  image:
    repository: rnld101/lavenbloom-frontend
    tag: "2.0.0"
  replicas: 1
  port: 80
  namespace: frontend
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi
