apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-service
  namespace: {{ .Values.journalService.namespace }}
  labels:
    app: journal-service
    tier: backend
spec:
  replicas: {{ .Values.journalService.replicas }}
  selector:
    matchLabels:
      app: journal-service
  template:
    metadata:
      labels:
        app: journal-service
        tier: backend
    spec:
      containers:
        - name: journal-service
          image: "{{ .Values.journalService.image.repository }}:{{ .Values.journalService.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.journalService.port }}
          envFrom:
            - secretRef:
                name: journal-service-secret
          resources:
            requests:
              cpu: {{ .Values.journalService.resources.requests.cpu }}
              memory: {{ .Values.journalService.resources.requests.memory }}
            limits:
              cpu: {{ .Values.journalService.resources.limits.cpu }}
              memory: {{ .Values.journalService.resources.limits.memory }}
