---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: journal-service-secret
  namespace: backend
spec:
  encryptedData:
    JWT_SECRET: AgB7IvNWmTd6HxKyWGtHNxtQ6Sg7fw9nAC2L5BqrdFFRbwYby8a3I0I2oJQ4K20K4majASVUbjYFNdDbU+DyUFzO1fPRa7x/3wEr8DpLEsztJUiTa+uT4aeqdJu8iU4+gRb3eFYiVTXm8oVznRMI57tdLxt6yhkdwExhhr7GH7BQLL3AwTkvOT4pfMZaaskBN+1Vw7zUst3eY3IIGv4lW2aY3FIDRrIJxwRnXv0u2jm0ksDqDDEVE4sAi/JKxWTe9PbcZ7VDsM5NPMnC5Tqyjp9/WGy4TRsfdvIO7a46vF5sRhYnEvJxHO2GO6AxcbtzZxDDpk+RAnAJOesy1SyB9sP9/5weaTfzQ3rlGzZmXcFwwlb//AyGE5YLR87dRAKGltciXIxSPALyA49P2ugRy34sfgYArpL5SZM0SRu+HLg17ltka78Pz3VZBt44LncPTn5qsh/PVT4dh8xBEX6HrLPV8plI/WUEjNv73GVaXninCbSRQIOQcNZhF6RTe5m+fffc8x+vq1/IXWYt+UCqSTVrWjmK6/LHsWGJK83+bFylpvqBZh6f/yG+LacBxI5jzRo2OsxMCOVmsmMq3MSizOLW8SdehXq45Zbtqe64w6+kJ8zrMsc+xIsWf3JH3wVst7i6twKUAUfudpYQ+Ora9JTUZONVkStB5a0r2E4RoWqWSpMhh33Kpp3d8uQ3I8dS5iuZdS6qwUmCYmm5GQ6Psc5SSA==
    POSTGRES_URI: AgApVdJ/AdjEqy++fxNyRDpsL8feHVAsrq1+X5wW2d4vaVqO+mpVW401JJ++USt/mN+vYm5dWVkJHEwQKoYc3aEzz+nv1s7jsLpAmc5jIJkWInsStEHpAcdBkBK1b6Ix1HeKt+mM0TFZu5a1i3JCpg/m46Dgs5YepHk5qNcghVoVHkOpV9wSZGkVdO0dR5rgR4RC+TDnQJ3VGpdAyXrTB1s7yVsMOXCIwzOfuDvC1Tz3IbnO443I/ulyGKbWfAlocgU3dRsIrb1CpysgxeslOOvKOMnqhGdWZ0gkPWBF0Scc1mbFpg5urUQhTe4s1P74sowz8Jj/2mh/YHXPGDmRQ/2wKkKJpMiDbXzg2OloPux29c2jZO4rkty7PlOrVI/a3K3AtX0xPqv5A0Zwfjx2iTOtHzBaxI/JITkqNj2R+PtPpnTLgTe3Ld2FVCAjoE1rdXFZsHNOrnD4rwcP7/xWx5uU4hq0nTsKqrxFbqzjjOXLxHYBwL6JWuyrAQ1yy/lkf/g1J3xmHue2oWNQ8BLbmZNJ9IjttzoqW+krBmVfX7OjYFbq1wgk+GDn4JrieeSRyST6Ql5efDt/sZf7lpst7wWSV0m8qQUvICtAoYe0j4GPs/58+UsUGWG5uADSEclr6WDcTJHswwP6uEGJPPzv4fUrXTVTAbQtIntIhR21p4dCvQ7tGFNzY2MAs7i0uLRqoSZ+SkEil4WcPL4q0l0S5bXY00RHs/VR1eQN85aemzMKnmNuSagaCuMwolGJYIz4RBEw+F7Fju2pSLRDkew+hqqOwBhd2r2avSbXQDHVmIAbzSNR82i3EqA=
  template:
    metadata:
      creationTimestamp: null
      name: journal-service-secret
      namespace: backend
    type: Opaque
