---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: journal-service-secret
  namespace: backend
spec:
  encryptedData:
    JWT_SECRET: AgCFHAEawvnmAyyTLbq9E0rlnmToWbT7lFzkOxUiZdZJg79qV3TUAd3yddDYS7xrZGUAGJLMTTHOmz2PIsPc4Caq5VgxBQ+jgvJPw7lvnRHWU8+WkkAxmhSZFlYyEwxpWA79MCXpvKlTSPeXQj9XXt24c2KaUG9QNIFuW9rHg+UpvFvzgGel9lp0SYFPMenDWAeEjzT+iCjr/vY/ocMZnn/jR2bHr1QUoy/414+HJbwk8IKDUnmrlc1HUnW5JghEawQKVS26JlF235l+rr18BbtvLscrKcqtDRbgwrsADZhaNK+A4PFBCnZx6D8KkcRsu7Bbl5AqfG9dJsUoRdy4xwigtzy/seQj7jZ71VOCsBeeae6TBnOWvcJlEyClu4+zlqCRVBAYvjBAyK2O+xQ/2sYEvpWLeEXl4uIVni4/uC5x6xya5tBDvrdHrAjoGcz1nOBLCoRCghWYaaqCaGaoT8DFY2MWU8bYDjPcSZ8jnzZcsOnFGYBf5aDsZvWvRwOKatH47hyLpkz5GmpriP9kPCeafHV9KQ4MRixXrnq5mKYbnwVZW5oXFEoy88XLEdCWhDL/GEcrLHbF7kg5P5vBxcasJz4wL5xJqSqAdcJPflVqjgEMJ4inFB/sxfouG4zrum7PpvJO08GuwFRvI5SMtGcakNlnQuHSU5bMLrzYMd65N1LDc/OhuXJ5t5ejjDWzPszkrNTdHNSG4FZBQ46Li52eng==
    POSTGRES_URI: AgBLZkQjJxFnR8DWq5tWzXpfAaVZwf9yOjgG4wO9MG4EKknqwbDjLimf6YwHKMpjjq00PHGhiDGl1+8S4o1cq1IZWTqRPXxWMeHn+CTCvdEmgj3HsuaNN8S5s8JR7jw9imRzGOmdLALu40wXOcmtey/7cljQA+ptJWjc3rXSmEi4GtYO1VNoJKk6mpKVmqXr33lziKUZvZsnohbaY2yNPbqUKEKYNu+x2utXpeHosod3OVeSI0Cn/3CLsb+rIW3oUwY0RgT1fvPMd/YdqAEGvOvwkTiL9PZcf7lKdBQG2fLZD/TZTJLKLhNrA32CiLA0cUO8hsnd4sl25PQmZVeI4K7frqw9lzsRjS9GLELVa7uqnae7z/krm4i4soxagizuGNlbfXteSQPcmU5Cs+sRILsuEgomiAofe9GP1Sx/7+xmSZUi0Kw2nV/pORPPYsEFAkljquDyWAInT1BGpzMQwPohTZnsUH4qtNTpWxayRpoRmhjTA77soWKewPw1SLpN4uYCoTvdZ6I8UwHDXwhKM6M1gl+BkkURZNbnuqNRvxWXJ+3OdNaPXdbZiSQguj5PBpblbEpiLsvK108soVt7IU+vjMsNNq+ktewjTNtKJLlZZIUwaF6zDyoz2Zow4b/lSwjwWrWyxFzKoJTxx4Ke45PdDdySHaG1sfsm/HQV0nCMaui2TI37gfZC4Z8XB30BbiDs32QaJk/YVbeU3zCr9pQKw8dhRG0W3ObHyCWpHiR7R82ZZaCqM8xwPPl5nbnfHRNjgVhyPOmlKI5sSWttr02dKz+8EwjDDqroJX/54pPGeTrGr2AaKgA=
  template:
    metadata:
      creationTimestamp: null
      name: journal-service-secret
      namespace: backend
    type: Opaque
