apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: {{ .Values.notification-service.namespace }}
  labels:
    app: notification-service
    tier: backend
spec:
  replicas: {{ .Values.notification-service.replicas }}
  selector:
    matchLabels:
      app: notification-service
      component: api
  template:
    metadata:
      labels:
        app: notification-service
        component: api
        tier: backend
    spec:
      containers:
        - name: notification-service
          image: "{{ .Values.notification-service.image.repository }}:{{ .Values.notification-service.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.notification-service.port }}
          envFrom:
            - secretRef:
                name: notification-service-secret
          resources:
            requests:
              cpu: {{ .Values.notification-service.resources.requests.cpu }}
              memory: {{ .Values.notification-service.resources.requests.memory }}
            limits:
              cpu: {{ .Values.notification-service.resources.limits.cpu }}
              memory: {{ .Values.notification-service.resources.limits.memory }}
