---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-service-secret
  namespace: backend
spec:
  encryptedData:
    POSTGRES_URI: AgAhEMsEQPkq5x+bna7wcQpVwk7b0HbaoM9SiLJXbKwPsz7/rI84XHisS8jbClcBcSGFEmDCUK30AebLAQyqavoiIo1ymCzYVObcOj1e66vYMtrO5JBV9CIgyLNbfkYsMQGgJaJbeNEnrdyTcsVzP42eZZAOVDNiIMMqwmN9ebzt0TXMYk0TJcjF+4ztlDrENe44ClEn/bR6CKa/60DMWLI9hvlnm7RINtzYnNigsSmxj3vPTuhq6R32ENZIEL6kbaQhKmUGclG5DvdJdeeSb5MQscURmUVNoETX0L3O6eLzqfPCHkquoaUBNfAF2wF4y5zLPVqAYWklCSuVLDQ0RS5EzaVP465rvp6oUqcQCpkEcsGcTzUVEk0kvF47mY4Tg5x6fl9kr8yWPjE+uXvtyZ7Q/tcA4QPOQsSmT+XfNkqCXteVENdr/gQ/0zuF1xDwz+CflqGAunomRzIzb/IPO9UnDNE4VoVeWFCs0yBDOavlRAB0kinXOyTFCS01Wuhox3EC30Z6TcoaIJxl2aUBFZoDMMYctT097GwxfJKl3H6mA8oX+VElTMyYNoLFOB1Av2L5bKsEd87uc7FBI8h1j04Tn/NhO59nHjSVIZmJr1+StEo+61Y8lvKRHOsGQB04tJqpolUfAhfqhHhjDs1KtKJyLXtUOXBWkW4FU8DjJDXeNcmjnHY/kvcZqIIpsENj/PM+ThPVWcChboqhKNpahMRP4XcKeFm80A2r3lxB7zmWu8q7VbNaq3cPFCmlErXtUmwZ9FECcwTQeC3OklmBExpGaA8ETjp1ITB2ZIQBh32uHp1zIsep7fcfJJoW3fRBYQRLqqoun83KRcY0Aw==
    REDIS_URI: AgCZRC28zz+QSZCSh1AiYO9kZSaX56l5iMWIrSUtOL3uoPRJIP7+dP5BY3jnjztPQFdlX3qjSwP1h6RHQ2+4RADfla5K2GvFRafYGbb8uT5W0YrgE+rZMVIMLL3DciD7y3wl/JxuFESWg2FJaH5ceAbsfe1j3rnoyz4gDWwh8tmJxxpkg29CMq17592WylMxq8DJh2sYsuGA+vITvfOrBvkEK158Psv4/6OyUn8H+dAjM6HQOD3gFwyl6/GVXhkhNzlfRnDgwT3Zl5xJRx+vtjMj3VIoF5qkLYjl8SfrKzVsF/MoRncC1MsRxtMSS1xFEELXo2tM/7mGrLc8irPXrITZOExpCgSegDf6uc1Lrjpa77/WP8u6mzIOoI1LxtnXBTIhqSfnIWuL4RiMv6KFf8+7j9ajFmoNzN5XeJNGGAJZlQbsjgh2JTT6YNVqs5KQIg36FX/ZMqfcqB5C29IVGjnsmQDJhTLuxQJztVwJmq899K69LDTwwhkY2Cs3zhpI8bEMZCgkZTxkUR2m3oUL6h31g6K2qzp9O8M5nH57/YUgEj8gpKAZg9NO5YuftXeysdNOo747cb54nVcHgdjDiiCqL4wop7hGMT1xtLP2NBDTpyxDnj6lsnM+YxNGd+cdrhTBPdGgo3XZDejqwslhe3vJsVjhbyM5on1zILtm5I+BiGOuIKJHB5MQlTTluoJX7N68Ru4pm5KMzCaSnmPETz8nkgbqx7nibHx99UO7UoL9CXTY5+F/W8WYyMvDK4K+FXZrfW2dhfXX1NGLI5yQ
  template:
    metadata:
      creationTimestamp: null
      name: notification-service-secret
      namespace: backend
    type: Opaque
