---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-service-secret
  namespace: backend
spec:
  encryptedData:
    POSTGRES_URI: AgCef2Cve8BHOuuXLpzmb9bLZ89sn+hD92+vhxL0Wh8V4pMDQs9Ih9wye8vVxkWUcOLIQ9Oq/CNbgQfvusz9PAwfhvbrCXhgRrPV9EHxZ/N49ajHGIyXIlBBnwZon6gDgP0Gc2R6i3Jtx1xDcSQWEaf4ciGONs2VWwDxSB0xdXYlTIFP/qf4TgAc+Tq8ZOkfte9Cp0niAcCD0MEi+SYSGHfQa0CbNUpQ+zXR/PlbtGqovEFLuGClJHr2QSqpaoqskMep9PuhJGSgiBrXWNt5Dkc3Fnk2u4TCLIyzigTVagU49K2XN5zBuuzDqHD8Xer8pb+rYUm5zC/0Dkkxy04Nuq+2QIJ6pH/BfdyzUo/+DbnGk2+J4iAamdJYnTmkmalmB90xEUfhltpGlkpjhhv5OHzjNU3tOtm+BRswbrhwGTkUQ+lqtV5wUpeuSuOwxbpTCQsa+sCgvhyE+aMKtK9rNjYoBWyRVWGTK2jt2dRkEvgzU46i5EMMFq1KN7qLEEnwROWNUH6Rt9aSzXBHzAp7JeYpeQ4BX/5ZhIYwzAlZHAUh1Q/Otst48cDDskOtQj5RBXYjdlWhMMrG5lBIHxCn3GA4H7GGFWvn0wJJHZ1VsbtZ6PiPr8zgsuTh9jRqXkzeigWU7Tke30illeeJPv4Al15fq1yf6OJ01HqXp3wv66n3P5u1XwHYJiospiGWuSb+ax7pCXLlr6smLba8wDgmMzNjDTedG7mC7QxpwoB7YmIWCUE4pXmUuiF15jXnUD9ALV7L9l0QyF2aRw8i8owxTM/VOnjgQn056Z+RSW9PvAg/4WrGJx+9Z0MiBlqcNFLoXGKZ6qLLomPxeR8uKg==
    REDIS_URI: AgAk+zcthjQCCACf1cDDTiy1dB5nvuc9NdTLU9fhAgvm1R6WDUnfTwzAUy6nyAoBfZk8JaA+nwuiEIAD8Xcw8bYZDZp9e5eR/YfbtmiqXlA5gMUvNsWoGH6pmbI8dL9iWS0JoooG2cqjwqsRep3KQnmiODG3xjslrMSWZDyG3ofbaf44Dur0VRs9anDImgGmEs6qSl+mQCdXTmEhoafWcTNHNlplz3kbn4yHx7rzsXaDT7X80jG7WJvpC/yy7K/n1x3Xg1583E9ruQs3xbiV6NkbNZr6pFuOX1d5vDh5i0gjXsFvPdSGHDmrkpRGQYe3IQ9CqNtXroY8+rtwRfFNemqmChdYFtef4RA0vUv8FV5aALlNiO9le05LGuwvJ08KIg2DZhdAsrziyEbvPY/0CrJDYi14GPEJ+VkPwmkJ6vK6HFEr0djZKbxa9ksIOV9YkdljLK4nQ+YIIE8+3S2jvthVkRFcP+Os8zPpmrzX6X4dGgUk11ODxsJ030sWkxKYkUhyDNxaW+NpdlZt0ucRRrEij0aehqMtI9DahIysoALfI+6BpOXSdMt6E0h4TV6OTxSJIZznEEjy3GCqShmgrF8firpdTJfI7H8pLOumoOUHav1VITuht6ndKZvsmI2zCqE7aPqUWAdgUnCXkfA1H8Wqd36zlzz5MpDtgtVV/WfMAe3kFxDujTpBsu5Ni1e4KnFA9GK8MKuEQIawoYuOEUlzaoJnseW7r0dUgay3GGkL8AhRkgAJfEDdAefajkpR7Mp1J/vf4VYCYcu3MxmB
  template:
    metadata:
      creationTimestamp: null
      name: notification-service-secret
      namespace: backend
    type: Opaque
