apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: backend
type: Opaque
data:
  POSTGRES_URI: "cG9zdGdyZXNxbDovL25vdGlmaWNhdGlvbnVzZXI6bm90aWZpY2F0aW9ucGFzc3dvcmRAbm90aWZpY2F0aW9uLWRiLmRiLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvbm90aWZpY2F0aW9uZGI="
  REDIS_URI: "cmVkaXM6Ly86cmVkaXNwYXNzd29yZEByZWRpcy5iYWNrZW5kLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzkvMA=="
