apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: {{ .Values.notificationService.namespace }}
type: Opaque
data:
  POSTGRES_URI: {{ .Values.secrets.postgresUri | b64enc | quote }}
  REDIS_URI: {{ .Values.secrets.redisUri | b64enc | quote }}
