apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: {{ .Values.notification-service.namespace }}
  labels:
    app: notification-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.notification-service.port }}
      targetPort: {{ .Values.notification-service.port }}
  selector:
    app: notification-service
    component: api
