journal-service:
  image:
    repository: lavenbloom-journal-service
    tag: latest
  replicas: 1
  port: 8000
  namespace: backend
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
db:
  namespace: db
  image: postgres:16-alpine
  replicas: 1
  port: 5432
  name: journaldb
  user: journaluser
  password: journalpassword
  storage:
    size: 5Gi
secrets:
  jwtSecret: supersecretjwtkey
  postgresUri: "postgresql://journaluser:journalpassword@journal-db.db.svc.cluster.local:5432/journaldb"
global:
  storageClass: nfs
