journalService:
  image:
    repository: rnld101/lavenbloom-journal-service
    tag: dev-c6f982f28bbd506b1475d2d933a4a8a6580fc8ef
  replicas: 1
  port: 8000
  namespace: backend
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
db:
  namespace: db
  image: postgres:16-alpine
  replicas: 1
  port: 5432
  storage:
    size: 5Gi
global:
  storageClass: nfs
