---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-service-secret
  namespace: backend
spec:
  encryptedData:
    JWT_SECRET: AgCVaBe2uD7Uv4zvx8m+SX4sWBxi9Z+3IuEC7jDM7ZKNNlxM6lEjGsPBDJ/FaasIMgEVmKSvsDkxgSbCLd+/c3DF0NE6dsfRzgU/csQJ2zgKTyUNGMNmTwFgvpWf7OH5+XYf6yNfa7U6bQwHuUUCZpfiVT7pUWp7F6Yx0R/ir7dnA69j3Bfqy3KG/azMGiyQnfoLsChVvlyPPDlXINKRAaNtZx3Y5LPG1LW/oxO/ak5KBpbKAuBshGw6M6oPQnj51iGgj1Sqmm63PT+uKbWHDRl5Gb2zk1ueNO/RYHUqoKzl9gxPF517NmP/W4hqhGED3dxW5r+b0xHeGgsfmgQlr4X+8+vl+212M9HHQ+UFnBC5wzlXpX1BTx+OVTRY8bdJo5L1IzknbrptFqieVyQGFuAriOZUzFq9BweAtsbAH33FRjyU0KVhRFwc8d+lrQaDPKo6gJgOZoStINwyfpIgtRUm1jS8/5H/N3YbSrae0EwPc4sJCztlWU3Qj4lFG5qrB0EueCCLg+c9Kq1QkPwnyft8KoT0BFEqQ5HQS2FVFqDvTMuHXCv3vLKOqwQG3ChSVuKTEAHrdjECiCdko4qw4UEvbA6XJeOHYstmqiNjaub1ZuOUOtu70XPDPr0JDxW4X85oE4lTOw7QzieQJ7RtUllh2qjwVTX2wHnAV5GOau1B0/BYHHfhKl8s2Oynl1z5dCfp3JXTe1wgXAe34IkxmcNVxw==
    POSTGRES_URI: AgB0UbHehd4QpHVXAKD3u+tHzJR2N28XweH4RJz4T/etL6kRGjnj89LQiahHKogLr28DjyI7lbs5m5nCxdDTAZQaJYMliCVeA5NOUDZ0EsDOgeDSBG01m02AaZfmx6X2XI1h/jghXifXDxOXaTjmdqnpoooaNnCN4DgvLx3QLh1QNPzEHeIwr6CHu/g4/472ozusfErN5mtuK8avZ9LKLstzvpFXX3q9/ddyS9oUufOD0yI56N1X4r64T6bl9Q6jgjWkf4oqh/BQaUkxEhkR4NgMpO83sLU07q4NjS39KieQQtTmQhKky8Sdth6zClkcA6lxPyzWkhJzZyC0X2NaBO0LN3UdsPKitqmwFTC6PQzZneVgffDXHypJeCw+rwRnCGs/RxwUyC17UN/xl37wM56RwUbMx5HUN0Ku+0xpfJeGuQ74188Kb9w7iTrdfL9J+e5bQioWqzj8QBhoBpW6LoW7d5QtfhU6JhAKn0WXhPRr2Viarr+1Xhx2bJG0rFV24OmnHu5z4XWbY3Kpdi2SZ0Dc2caUzYhb9V2A5W/z19Ou0mLmm/7HmA+LieApd6iSIA72eMUZPwzo9vjTH6eg0Dyfbn9qXh26VhXvSPwT4IjSk6vK2vdLZzEUQDZB4ekK23IC2JkRLRf8CsTOYBNPN4lxNcTLz+FZsQwJyqY8Fhtw4CuXivD2AU/T6TWSr17chEz8PBVbVv2VOLsGgMjtGfYqGFUHDVmYhRYyO9sDGSUIyXcR68jToE7bAfHH6c8KiNlWWMl1ykwcYm/W/R4Y0FiNX+cSAi34jQ5Pvs4=
  template:
    metadata:
      creationTimestamp: null
      name: auth-service-secret
      namespace: backend
    type: Opaque
