---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-service-secret
  namespace: backend
spec:
  encryptedData:
    JWT_SECRET: AgAg+U5hMePbCmLNNogNAv9OT7oRXRsfnjMw2aEAj0Wnv6YxWyLho/JIGjP/LnuOmRhXMB06/rht/pyzrARtwa3Iq6KiWDQXXN3OB2nOdVE9wMpc6HZAC0Fw5Eu+dS25O/zTO/PYXM8aMFVor7NSS7WMu0RrjHwmngk83T/eoOVw66PEMstQ1rcCygZMOQXbRso8oZEia6mNf3/ccLvFIJyZThFPFCm6N37r0c56NrF6pXbn8+MBfBhOdRiKmw1bV6ZdDbYDaVcxBAyMG/+ABKYcIlHASk+pXzkRqfE4+uuwr2RIN8sUdjMW+NxuCEJ4RWCi7FeBMqnKAWGMrivPA2mNMFF3qje8IVR/tDcjLvMcn5IOLHhzMkhhd8Eny6rdF65EJAmFPTYcNG6Q4A7Ee92/Q5YIDqGUkRCNWoHJZKpHNXc98iMsjr2bphQsH+kAmBVNTZHTvB2gg0iOOCx42CE9fqAEJOZFyHmiCF74i7pWlEaEkGQHFehxZjjKQKGP2Xx2P7hjuQtjSQ2z3EmoYWwz6WvYEcv9vNAf6hwk4neBzDuE1idICnokS0+oIpYZ4SsIxT+jz/PGnr3TunuSzfEiKDnikt2k99HsNDNJ+RBtWEYJzZIT/NY9fAhVRNNGF6B9TDOAIoBVA2Fx9BJTPAh9z/9iacw98WYgVKvTGlDeaYvbXxg+dJ4YkjYr+Oxq1pAcTKWQ45Um7KelEwcNqOWbVg==
    POSTGRES_URI: AgC4Rts715JCB77+dFvnniRhqcxSf4ACOlcB1iFHZM94/cZyS65qeqZULPHArUSZyyjlVKCG/tTU04KzRFfyF748UOBnUB6KXMZ8NaczVa8xkUhDGk2lmDuNwPJy3KtQXviqgTP6MSHWMWtvUxXniiutVpUAUwiU4F7M5dPC77CjsVF46V9V4NERFg2Q4BNmBMY0ZGNBTHO8D5ViqxJUlKUnN6acxwfjuPybUkxDHaUzdVqLsQopNpzKLCwP0JMxRvXTYnKd1y1SJQGPMz5Ourw55X8zu+pv7NpgZgTeEweGcdS6zzxW5HzhrKE5D2xTXNBc1ZZrB2cK2UYXzDldL8pClTLyVe6NuMew5tiu/8lvxvXOoUE+gECpoYFDhC7uoGpn4270raydPD0h+CTk5mYeRN+lcrnJrYLLP9mlVGmi6YdzucX0Afzp0r+8+1VL2kop2EUrRLCfu2tTZqo6Ft8aas0tREgInuQ34qkpGn19ex/6AqvXNNKkUkM5JEdWp7mcLPADF2zpoIDmav0R1NQcsI3PftS6M50PKOhLBhBHlipwHepVHA5PgQei7nh3cDF82pGVFvuEGBvPOCEMAW4C1fa13/n30Pmf2lrwG2UvZ32UiMV85gVmQ9lSnqnxqs+tJPFqhPsPUyJp8ArxoR7dp1J4oNE3qxWW/FlPJoJijcKwuqVOopmllNldS2XLbKVYJE9Xpt4Ob4xdQ5eQKNs3aaIdLS3BUvT22ThT4SgfY2GUvmLOOy8euuxxjN23YUPBGrXY5Ey1hhfhvP03wNYYEdBQAi6caBOHdJ0=
  template:
    metadata:
      creationTimestamp: null
      name: auth-service-secret
      namespace: backend
    type: Opaque
