apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: backend
type: Opaque
data:
  POSTGRES_URI: "cG9zdGdyZXNxbDovL2F1dGh1c2VyOmF1dGhwYXNzd29yZEBhdXRoLWRiLmRiLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvYXV0aGRi"
  JWT_SECRET: "c3VwZXJzZWNyZXRqd3RrZXk="
