apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: {{ .Values.auth-service.namespace }}
type: Opaque
data:
  POSTGRES_URI: {{ .Values.secrets.postgresUri | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
