authService:
  image:
    repository: rnld101/lavenbloom-auth-service
    tag: dev-dab9e8cdafd789972c948b1db8e2c3a7520092cc
  replicas: 1
  port: 8000
  namespace: backend
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
db:
  namespace: db
  image: postgres:16-alpine
  replicas: 1
  port: 5432
  storage:
    size: 5Gi
global:
  storageClass: nfs
