authService:
  image:
    repository: rnld101/lavenbloom-auth-service
    tag: dev-2192484c87233cf4a58a84c442411c0d366dca7d
  replicas: 1
  port: 8000
  namespace: backend
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
db:
  namespace: db
  image: postgres:16-alpine
  replicas: 1
  port: 5432
  storage:
    size: 5Gi
global:
  storageClass: nfs
auth-service:
  image:
    tag: dev-d418960955bd806298b327a0cc14378a60e556b8
